
```{r}
# Import libraries
library(ggplot2)
library(sf)
library(spdep)
library(Matrix)
library(MASS)
```

```{r}
# Load data
Admin1Graph <- read.table("Admin1Graph.txt")
Admin2Graph <- read.table("Admin2Graph.txt")
load("Admin1Geography.RData")
load("Admin2Geography.RData")
DirectEstimates <- read.table("DirectEstimates.txt")
```

```{r}
## plotAreaCol
# This functions plots the values and saves the figure to the specified file.
# It is advisable to not plot directly in R since it will take a long time.
# The arguments are:
#   fNamme: file name for saving figure
#   width: width of figure in inches
#   height: height of figure in inches
#   estVal: the k values to be plotted on geoMap
#   geoMap: the map containing k regions
#   leg: name to use on top of legend
#   colLim: control lower limit and upper limit of color scale (colLim = c(lowVal, highVal))
plotAreaCol = function(fName, width, height, estVal, geoMap, leg, colLim = NULL){
  if(is.null(colLim)){
    colLim = range(estVal)
  }
  
  # Set up data object for plotting
  nigeriaMapTmp = geoMap
  nigeriaMapTmp$MCV1 = estVal
  
  # Plot
  map = ggplot() +
    geom_sf(data = nigeriaMapTmp,
            aes(fill = MCV1),
            color = 'gray', size = .2)+
    scale_fill_viridis_c(direction = 1,
                         begin = 1,
                         end = 0,
                         limit = colLim,
                         name = leg) + 
    theme(text = element_text(size=40),
          legend.key.height = unit(4, 'cm'),
          legend.key.width  = unit(1.75, 'cm'))
  ggsave(filename = fName,
         plot = map,
         width = width, 
         height = height,
         #dpi = 227
         dpi = 150
         )
}
```


----------PROBLEM 1----------

a) ----------

Implement matrices 
```{r}
N_1 <- as.matrix(Admin1Graph)
N_2 <- as.matrix(Admin2Graph)
```

Compute the Precision matrices
```{r}
# Create R from N
R_1 <- -N_1  # Set off-diagonal to -1 where N_ij is 1
R_2 <- -N_2
diag(R_1) <- rowSums(N_1)  # Set diagonal entries to the number of neighbors
diag(R_2) <- rowSums(N_2)

# Define the precision parameter, t (example: t = 1)
tau_1 <- 1
tau_2 <- 1

# Compute Q
Q_1 <- tau_1 * R_1
Q_2 <- tau_2 * R_2

n1 = dim(Q_1)
n2 = dim(Q_2)
```

Computing rank and determining symmetry
```{r}
check_Rank_and_Symmetry <- function(q, admin_nr){
  cat("admin ", admin_nr,": \n")
  if (!(isSymmetric(q))) {
    stop("Q not symmetric")
  }
  cat("dim(Q) = ", dim(q),"\n")
  cat("rank(Q) = ", rankMatrix(q)$rank,"\n")
}
check_Rank_and_Symmetry(Q_1, 1)
cat("\n")
check_Rank_and_Symmetry(Q_2, 2)
```

Compute the proportion of non-zero elements and display the sparsity pattern
```{r}
number_of_zeros_1 <- sum(Q_1 == 0)
number_of_zeros_2 = sum(Q_2 == 0)
cat("number of zero elements Q_1: ", number_of_zeros_1, "\n")
cat("number of zero elements Q_2: ", number_of_zeros_2)

# Plotting the sparsity pattern
image(1:n1, 1:n1, Q_1 != 0, col = c("black", "cyan"), axes = TRUE, xlab = "col", ylab = "row")
image(1:n2, 1:n2, Q_2 != 0, col = c("black", "cyan"), axes = TRUE, xlab = "col", ylab = "row")

```



b) ----------

Initialize Besag model simulator
```{r}
# sampler function
simulator.besag = function(mu, Q_stable, epsilon = 0.001){
  n = nrow(Q_stable)
  L = chol(Q_stable)
  z = rnorm(n)
  x = solve(L, z)
  x_star = x - mean(x) * rep(1, length(x))
  return(x_star)
}
```

create simulations
```{r}
set.seed(123)
# parameters
epsilon_1 <- 0.001
Q_stable_1 = Q_1 + epsilon_1 * diag(nrow(Q_1))
mu_1 <- rep(0, nrow(Q_stable_1))

# Besag simulations
admin1_besag_simulation_1 = simulator.besag(mu_1, Q_stable_1, epsilon_1)
admin1_besag_simulation_2 = simulator.besag(mu_1, Q_stable_1, epsilon_1)

# N_37(0, I) simulations
admin1_stdnorm_simulation_1 = rnorm(nrow(Q_stable_1))
admin1_stdnorm_simulation_2 = rnorm(nrow(Q_stable_1))
```

Plot simulations
```{r}
plotAreaCol(fName = "admin1_besag_simulation_1.jpeg", width = 15, height = 11, estVal = admin1_besag_simulation_1, geoMap = nigeriaAdm1, leg = "", colLim = c(-3,3))
plotAreaCol(fName = "admin1_besag_simulation_2.jpeg", width = 15, height = 11, estVal = admin1_besag_simulation_2, geoMap = nigeriaAdm1, leg = "", colLim = c(-3,3))
plotAreaCol(fName = "admin1_stdnorm_simulation_1.jpeg", width = 15, height = 11, estVal = admin1_stdnorm_simulation_1, geoMap = nigeriaAdm1, leg = "", colLim = c(-3,3))
plotAreaCol(fName = "admin1_stdnorm_simulation_2.jpeg", width = 15, height = 11, estVal = admin1_stdnorm_simulation_2, geoMap = nigeriaAdm1, leg = "", colLim = c(-3,3))
```



c) ----------

create simulations
```{r}
set.seed(123)

# parameters
epsilon_2 <- 0.001
Q_stable_2 = Q_2 + epsilon_2 * diag(nrow(Q_2))
mu_2 <- rep(0, nrow(Q_stable_2))

# Besag simulations
admin2_besag_simulation_1 = simulator.besag(mu_2, Q_stable_2, epsilon_2)
admin2_besag_simulation_2 = simulator.besag(mu_2, Q_stable_2, epsilon_2)

# N_37(0, I) simulations
admin2_stdnorm_simulation_1 = rnorm(nrow(Q_stable_2))
admin2_stdnorm_simulation_2 = rnorm(nrow(Q_stable_2))
```

Plot simulations
```{r}
plotAreaCol(fName = "admin2_besag_simulation_1.jpeg", width = 15, height = 11, estVal = admin2_besag_simulation_1, geoMap = nigeriaAdm2, leg = "", colLim = c(-3,3))
plotAreaCol(fName = "admin2_besag_simulation_2.jpeg", width = 15, height = 11, estVal = admin2_besag_simulation_2, geoMap = nigeriaAdm2, leg = "", colLim = c(-3,3))
plotAreaCol(fName = "admin2_stdnorm_simulation_1.jpeg", width = 15, height = 11, estVal = admin2_stdnorm_simulation_1, geoMap = nigeriaAdm2, leg = "", colLim = c(-3,3))
plotAreaCol(fName = "admin2_stdnorm_simulation_2.jpeg", width = 15, height = 11, estVal = admin2_stdnorm_simulation_2, geoMap = nigeriaAdm2, leg = "", colLim = c(-3,3))
```



d) ----------

Implement variance sampler
```{r}
simulate.besag.variance <- function(n_samples, Q, area_number, mu = 0, epsilon = 0.001){
  samples = matrix(0, nrow = n_samples, ncol = ncol(Q))
  for (i in 1:n_samples){
    samples[i,] = simulator.besag(mu, Q, epsilon)
  }
  variances_vec = apply(samples, 2, var)
  correlation_vec <- cor(samples[, area_number], samples)
  return(list("variances"=variances_vec, "correlation"=c(correlation_vec)))
}
```

compute simulations
```{r}
set.seed(123)
admin2_besag_VC_simulation = simulate.besag.variance(100, Q = Q_stable_2, area_number = 150, mu = 0, epsilon = 0.001)
```

Plot simulations
```{r}
plotAreaCol(fName = "admin2_besag_var_simulation.jpeg", width = 15, height = 11, estVal = admin2_besag_VC_simulation$variances, geoMap = nigeriaAdm2, leg = "var", colLim = c(0,1))
plotAreaCol(fName = "admin2_besag_corr_simulation.jpeg", width = 15, height = 11, estVal = admin2_besag_VC_simulation$correlation, geoMap = nigeriaAdm2, leg = "corr", colLim = c(-1,1))

```




-----PROBLEM 2------

a) 

Get data vectors
```{r}
expit = function(x){exp(x)/(1 + exp(x))}
logit = function(p){log(p/(1-p))}

DirectEstimates_admin1 = DirectEstimates$V1[2:length(DirectEstimates$V1)]
DirectEstimates_obs = as.numeric(DirectEstimates$V2[2:length(DirectEstimates$V2)])
DirectEstimates_stdDev = as.numeric(DirectEstimates$V3[2:length(DirectEstimates$V3)])
```

Plot observed proportions
```{r}
plotAreaCol(fName = "DirectEstimation_obs.jpeg", width = 15, height = 11, estVal = expit(DirectEstimates_obs), geoMap = nigeriaAdm1, leg = "", colLim = c(0,1))
```


b) ---------

construct V and define function that samples from N(y, V^-1) and calculates median + coefficient of variation
```{r}
sigma = 100

# compute new cov matrix for X|Y
V = DirectEstimates_stdDev * diag(nrow = length(DirectEstimates_stdDev))
W = matrix(0, nrow = nrow(V), ncol = ncol(V))
for (i in 1:nrow(V)){W[i,i] = sigma**2/(sigma**2 + V[i,i])}
X_cond_Y_cov = W %*% V

# Compute new mean
X_cond_Y_mean = W %*% DirectEstimates_obs
```

sample values
```{r}
set.seed(123)
#samples.2b = sample.normal(100)
samples.2b = expit(mvrnorm(n = 100, mu = X_cond_Y_mean, Sigma = X_cond_Y_cov))
median.2b = apply(samples.2b, MARGIN = 2, median)
mean.2b = apply(samples.2b, MARGIN = 2, mean)
stdev.2b = sqrt(apply(samples.2b, MARGIN = 2, var))
cv.2b = stdev.2b/mean.2b
```

plot
```{r}
plotAreaCol(fName = "admin1_median_2b.jpeg", width = 15, height = 11, estVal = median.2b, geoMap = nigeriaAdm1, leg = "median", colLim = c(0,1))
plotAreaCol(fName = "admin1_cv_2b.jpeg", width = 15, height = 11, estVal = cv.2b, geoMap = nigeriaAdm1, leg = "CV", colLim = c(0,0.5))
```



c) ----------















